name: CI

# Controls when the action will run. 
on: 
  # Triggers the workflow on push or pull request events but only for the master branch
  [push, pull_request]

# [Building and testing Node.js](https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs)
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#   build:
#     runs-on: ubuntu-18.04
#     strategy:
#       matrix:
#         node-version: [12.x]
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: npm ci
#         run: npm ci
#       - name: npm run build
#         run: CI=true npm run build

#   test:
#     runs-on: ubuntu-18.04
#     strategy:
#       matrix:
#         node-version: [12.x]
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: npm ci
#         run: npm ci
#       - name: npm test
#         run: CI=true npm test -- --coverage --testResultsProcessor jest-sonar-reporter
#       - name: Archive code coverage report
#         uses: actions/upload-artifact@v2
#         with:
#           name: code_coverage_artifact
#           # Why use a wild card * ?
#           # "If a wildcard pattern is used, the path hierarchy
#           # will be preserved after the first wildcard pattern."
#           # [upload-artifact](https://github.com/actions/upload-artifact#upload-using-multiple-paths-and-exclusions)
#           path: "*coverage/"
#           retention-days: 1
#       - name: Archive Sonar compatible code coverage report
#         uses: actions/upload-artifact@v2
#         with:
#           name: sonar_code_coverage_artifact
#           path: "*reports/"
#           retention-days: 1

  generate_docs:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci
        run: npm ci
      - name: npm run docs
        run: npm run docs
      - name: Archive generated documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation_artifact
          path: "*docs/"
          retention-days: 1

  # sonarcloud:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #       with:
  #         # Disabling shallow clone is recommended for improving relevancy of reporting
  #         fetch-depth: 0
  #     - name: Download code coverage report artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: code_coverage_artifact
  #     - name: Download Sonar compatible code coverage report artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: sonar_code_coverage_artifact
  #     - name: SonarCloud Scan
  #       uses: sonarsource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy_docs:
    needs: generate_docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create branch docs
        run: |
          git checkout docs
          git rm -rf .
      - name: Download documentation artifact
        uses: actions/download-artifact@v2
        with:
          name: documentation_artifact
      - name: Create branch docs
        run: |
          ls -a
          git add docs/
          git config --global user.name 'DamienToomey'
          git config --global user.email 'DamienToomey@users.noreply.github.com'
          git remote set-url origin https://DamienToomey:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -m "Deploying docs"
          git push origin docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # [Push to origin from GitHub action](https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action)
      # - name: Deploy docs folder to github pages
      #   uses: JamesIves/github-pages-deploy-action@3.7.1
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH: docs # The branch the action should deploy to.
      #     FOLDER: "docs" # The folder the action should deploy.
      #     CLEAN: true # Automatically remove deleted files from the deploy branch
  # Activate GitHub Pages: Settings > Scroll down to GitHub Pages > Select branch and root
  # [Configuring a publishing source for your GitHub Pages site](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source)

# [caching](https://github.com/actions/cache/blob/main/examples.md#using-multiple-systems-and-npm-config)
# [caching](https://dev.to/mpocock1/how-to-cache-nodemodules-in-github-actions-with-yarn-24eh)
# [run jobs in Docker containers](https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs#running-on-a-different-operating-system)
# [sonarcloud-github-action](https://github.com/SonarSource/sonarcloud-github-action)

# Code quality github action: https://github.com/peterjgrainger/action-create-branch/blob/master/.github/workflows/codeql-analysis.yml