name: CI

# Controls when the action will run. 
on: 
  # Triggers the workflow on push or pull request events but only for the master branch
  [push, pull_request]

# [Building and testing Node.js](https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs)
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci
        run: npm ci
      - name: npm run build
        run: CI=true npm run build

  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci
        run: npm ci
      - name: npm test
        run: CI=true npm test -- --coverage --testResultsProcessor jest-sonar-reporter
      - name: Archive code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code_coverage_artifact
          path: coverage/
          retention-days: 1
      - name: Archive Sonar compatible code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: sonar_code_coverage_artifact
          path: reports/
          retention-days: 1

  docs:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci
        run: npm ci
      - name: npm run docs
        run: npm run docs
      - name: Archive generated documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation_artifact
          path: docs/
          retention-days: 1

  sonarcloud:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Download Sonar compatible code coverage report
        uses: actions/download-artifact@v2
        with:
          name: sonar_code_coverage_artifact
          path: reports/
      - name: ls
        run: ls reports
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

# [caching](https://github.com/actions/cache/blob/main/examples.md#using-multiple-systems-and-npm-config)
# [caching](https://dev.to/mpocock1/how-to-cache-nodemodules-in-github-actions-with-yarn-24eh)
# [run jobs in Docker containers](https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs#running-on-a-different-operating-system)
# [sonarcloud-github-action](https://github.com/SonarSource/sonarcloud-github-action)